export const ALL_USERS = 'ALL_USERS';
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS';

export const USER_BY_ID = 'USER_BY_ID';
export const USER_BY_ID_SUCCESS = 'USER_BY_ID_SUCCESS';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const REMOVE_USER = 'REMOVE_USER';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';

export const ALL_ADMINS = 'ALL_ADMINS';
export const ALL_ADMINS_SUCCESS = 'ALL_ADMINS_SUCCESS';


